# NOTE: Generated By HttpRunner v3.1.8
# FROM: .\har\index.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseIndex(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/module/searchtags")
            .get("https://office.safe.360.cn/module/searchtags")
            .with_params(
                **{
                    "inst_type": "0",
                    "m2": "bdac9c5161c743c2f280cadf3398e35272963b712974",
                    "mid": "545623be9cff9c7c1486c09dbc9b28a3",
                    "q": "mTJx2OTVQbcacf925+s/Mz8gnPjBlRSUuMZUNSI2SZ5urh30hCkGDKVrF0LCzbL/zPwrtuSoN4THBTXrDF184MBvCI06rqfO7dMrkW/bjsL1qz1xDzvyBPrhSUtDVzz4haTn6HlK0FTARsHw3OW7pz3vDV/KB2SMsinxLJC9OmQ=",
                    "rand": "129977",
                    "secore_inst_type": "3",
                    "secore_ver": "13.1.5270.0",
                    "sign": "7b793723f162777d0f0a3a7bc649c17d",
                    "timestamp": "1649234736",
                    "version": "2.0.0.1231",
                }
            )
            .with_headers(
                **{
                    "Host": "office.safe.360.cn",
                    "Accept": "*/*",
                    "Cookie": "Q=u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5;T=s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1;S=",
                }
            )
            .with_cookies(
                **{
                    "Q": "u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5",
                    "T": "s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1",
                    "S": "",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.errno", 0)
            .assert_equal("body.errmsg", "")
            .assert_equal("body.type", 0)
            .assert_equal("body.t_str", "")
        ),
        Step(
            RunRequest("/banner/lists")
            .get("https://office.safe.360.cn/banner/lists")
            .with_params(
                **{
                    "inst_type": "0",
                    "m2": "bdac9c5161c743c2f280cadf3398e35272963b712974",
                    "mid": "545623be9cff9c7c1486c09dbc9b28a3",
                    "q": "uCC2S5CSBlXpG0TUOQv1qalD2hAY1cNCnm8VPAJB3Di7h4deiOZcgrd5MQKKlEqmsID/fXpXtxQX/dMaWYQqFmNUj+feaSxwYuzOS4TbPA7J/NevOMih2/9Rs+IaHkFc0zPXLkrPF6V+2qjZ1iMb/S8Zqy4xa/wdoYXhrG34Oxo=",
                    "rand": "130029",
                    "secore_inst_type": "3",
                    "secore_ver": "13.1.5270.0",
                    "sign": "e569d4fb0afe5e68e4827fa509c34230",
                    "timestamp": "1649234736",
                    "version": "2.0.0.1231",
                }
            )
            .with_headers(
                **{
                    "Host": "office.safe.360.cn",
                    "Accept": "*/*",
                    "Cookie": "Q=u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5;T=s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1;S=",
                }
            )
            .with_cookies(
                **{
                    "Q": "u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5",
                    "T": "s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1",
                    "S": "",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.errno", 0)
            .assert_equal("body.errmsg", "")
            .assert_equal(
                "body.data",
                "fvTprPbDNPUwBlGITthwlNkchSlIBO6YaYnbIqKwHfNKxgMkKtPYqhzARWk1Gss91TrwrxgZsYa401cj0NMoHesWvxHbg6i+sZZFEdJmdzghN5QeMZHhMTadzDCA6Z3uAFlJ7tgrJwmc8a/gkBYrrj8dUgFZnZmNZSPCWQvcMws=",
            )
            .assert_equal("body.type", 1)
            .assert_equal("body.t_str", "")
        ),
        Step(
            RunRequest("/tab/lists")
            .get("https://office.safe.360.cn/tab/lists")
            .with_params(
                **{
                    "inst_type": "0",
                    "m2": "bdac9c5161c743c2f280cadf3398e35272963b712974",
                    "mid": "545623be9cff9c7c1486c09dbc9b28a3",
                    "q": "sig+3KmEMJO9CXqKDbsq0ZhvfzFhqIsevOqwBSmYmJUyjWTWwd/6Kr5cxWIEaF7FDL/2NzY5Czt4Nv8lrkB+AUo0N5LNBYn4jv8SfeFqMeEoBYmcQjHNd9QhlVjbHG1RDgfIfhwwiZcmnZ8dVuMglfVy1ZbaS6Fl2Z5TbgTsKwE=",
                    "rand": "130029",
                    "secore_inst_type": "3",
                    "secore_ver": "13.1.5270.0",
                    "sign": "a3d96fbb125af2ca5c85630bf51f1773",
                    "timestamp": "1649234736",
                    "version": "2.0.0.1231",
                }
            )
            .with_headers(
                **{
                    "Host": "office.safe.360.cn",
                    "Accept": "*/*",
                    "Cookie": "Q=u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5;T=s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1;S=",
                }
            )
            .with_cookies(
                **{
                    "Q": "u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5",
                    "T": "s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1",
                    "S": "",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.errno", 0)
            .assert_equal("body.errmsg", "")
            .assert_equal("body.type", 0)
            .assert_equal("body.t_str", "")
        ),
        Step(
            RunRequest("/search/scategory")
            .get("https://office.safe.360.cn/search/scategory")
            .with_params(
                **{
                    "inst_type": "0",
                    "m2": "bdac9c5161c743c2f280cadf3398e35272963b712974",
                    "mid": "545623be9cff9c7c1486c09dbc9b28a3",
                    "q": "tqALIO/qXw+Rz3YbIaUIP6BpHFYTbi3U1NOdFmDz9ZMfz/jydfWO9g5S8q9pGp1tawvwLoXcIBT+9jcEK+fx/r0+Rem1tSFMVpNCRiRfGbaxRvKNOur8HfIc9cCX/ifKAk9UAdI6r1lkeJD8g0Ka2zKGl2NON5IUzVonr2cN5XY=",
                    "rand": "129977",
                    "secore_inst_type": "3",
                    "secore_ver": "13.1.5270.0",
                    "sign": "4f9a2f2a1acce9b5cdc45b3eade3fdb8",
                    "timestamp": "1649234736",
                    "version": "2.0.0.1231",
                }
            )
            .with_headers(
                **{
                    "Host": "office.safe.360.cn",
                    "Accept": "*/*",
                    "Cookie": "Q=u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5;T=s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1;S=",
                }
            )
            .with_cookies(
                **{
                    "Q": "u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5",
                    "T": "s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1",
                    "S": "",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.errno", 0)
            .assert_equal("body.errmsg", "")
            .assert_equal(
                "body.data",
                "PMUEFzKNnCH5TBU9ZWuG2wL/vQ3bThHfZq2Ws8tlhQLveKuZcFnWKzDlWumm9f/ihOOHGZS4sQhrAqS5LZQ5BxcCYmYuuJYFMXFARe48Deh7SVVyPSDz57j3zls3+e4UG+FPPVX/mebG0GbnztIRuAlS8nOQJRH+0jIk6T0V4e8=|&|xvGXXTOj25H7oZFIwkzHYpZqfXfSZNv+70y2MFXLqrp1GsKEKEQkFS7p+wcRoGbPvaqEmNIjPMJ4lFQw+egIrGiXWaQKDP7+y4jB/lxYsV3NLhDfbtVcGQTd8PVcgWgKaKmY83rUSw0V4SVywK4JjVbyTM50lr/78m5+a8+rSgo=|&|cnDgOkv4xaDFfJfg7RFVRCvXjLHilZH3JnBoqDy6d+bIgf2SqQxVUTrc1tJxmszkdOGzLN/TQ5/jlV7ev0fsMUpC1oX08/gtCicaBNfM09oQcQgbEbh2zgl9ALw/ae6busMPw2ytwSVtOhe0fYd6VVZ54hkx4qX5Kos5mwWLc3U=",
            )
            .assert_equal("body.type", 1)
            .assert_equal("body.t_str", "")
        ),
        Step(
            RunRequest("/vip/status")
            .get("https://office.safe.360.cn/vip/status")
            .with_params(
                **{
                    "inst_type": "0",
                    "m2": "bdac9c5161c743c2f280cadf3398e35272963b712974",
                    "mid": "545623be9cff9c7c1486c09dbc9b28a3",
                    "q": "QY4dRug2lmZSn7Gnq21Oz7y9d2Tmaubb+i8njw8ex5kS8PtUxjQw0KAifXY01MGHFx/IdNLCl2YI1KXWRoNNXiW3KgMDW+7Cr3FYiSVF4CnhI7jQ0m4qt8MonwLBSzNvTcoxoYKa8gPEoxFP8QbbvlWB4CUZpM+8sBzX9KWj2/0=",
                    "rand": "130029",
                    "secore_inst_type": "3",
                    "secore_ver": "13.1.5270.0",
                    "sign": "7417af0a3da186d99895d6134dc20971",
                    "timestamp": "1649234736",
                    "version": "2.0.0.1231",
                }
            )
            .with_headers(
                **{
                    "Host": "office.safe.360.cn",
                    "Accept": "*/*",
                    "Cookie": "Q=u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5;T=s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1;S=",
                }
            )
            .with_cookies(
                **{
                    "Q": "u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5",
                    "T": "s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1",
                    "S": "",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.errno", 0)
            .assert_equal("body.errmsg", "")
            .assert_equal("body.type", 0)
            .assert_equal("body.t_str", "")
        ),
        Step(
            RunRequest("/index/data")
            .get("https://office.safe.360.cn/index/data")
            .with_params(
                **{
                    "inst_type": "0",
                    "m2": "bdac9c5161c743c2f280cadf3398e35272963b712974",
                    "mid": "545623be9cff9c7c1486c09dbc9b28a3",
                    "q": "H7nT+GnboOoM2pNXOpKPuYN5u+iM6akjoOmPj1rXrNNNRVo7pwrzT9rYg4xy6GUqNK0C67wc1Vkhut8ZVD051nzF4LhIz3bIT6+/IDVYmbZaKv+EakS2nVhPm8GQDtI75cFkBT9d7+cvRVC2QDvLZsvZm4/uQnPOj5VycNXSHPc=",
                    "rand": "130029",
                    "secore_inst_type": "3",
                    "secore_ver": "13.1.5270.0",
                    "sign": "c8e0fdca3b1d52f12e674423f015d2ea",
                    "timestamp": "1649234736",
                    "version": "2.0.0.1231",
                }
            )
            .with_headers(
                **{
                    "Host": "office.safe.360.cn",
                    "Accept": "*/*",
                    "Cookie": "Q=u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5;T=s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1;S=",
                }
            )
            .with_cookies(
                **{
                    "Q": "u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5",
                    "T": "s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1",
                    "S": "",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
            .assert_equal("body.errno", 0)
            .assert_equal("body.errmsg", "")
            .assert_equal("body.type", 0)
            .assert_equal("body.t_str", "")
        ),
    ]


if __name__ == "__main__":
    TestCaseIndex().test_start()
