# NOTE: Generated By HttpRunner v3.1.8
# FROM: .\har\index.har
# -*- coding: big5 -*-

from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseIndex(HttpRunner):

    config = Config("推荐分类列表").verify(False)

    teststeps = [
        Step(
            RunRequest("/tab/lists")
                .get("https://office.safe.360.cn/tab/lists")
                .with_params(
                **{
                    "inst_type": "0",
                    "m2": "bdac9c5161c743c2f280cadf3398e35272963b712974",
                    "mid": "545623be9cff9c7c1486c09dbc9b28a3",
                    "q": "sig+3KmEMJO9CXqKDbsq0ZhvfzFhqIsevOqwBSmYmJUyjWTWwd/6Kr5cxWIEaF7FDL/2NzY5Czt4Nv8lrkB+AUo0N5LNBYn4jv8SfeFqMeEoBYmcQjHNd9QhlVjbHG1RDgfIfhwwiZcmnZ8dVuMglfVy1ZbaS6Fl2Z5TbgTsKwE=",
                    "rand": "130029",
                    "secore_inst_type": "3",
                    "secore_ver": "13.1.5270.0",
                    "sign": "a3d96fbb125af2ca5c85630bf51f1773",
                    "timestamp": "1649234736",
                    "version": "2.0.0.1231",
                }
            )
                .with_headers(
                **{
                    "Host": "office.safe.360.cn",
                    "Accept": "*/*",
                    "Cookie": "Q=u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5;T=s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1;S=",
                }
            )
                .with_cookies(
                **{
                    "Q": "u%3DYYNO..%26n%3Dnnyyoo__%26le%3D%26m%3DZGpmWGWOWGWOWGWOWGWOWGWOZwN5%26qid%3D3286970398%26im%3D1_t0168deca91e10180f2%26src%3Dpcw_guard_safe_weixin%26t%3D5",
                    "T": "s%3D8139957378a18568e8bfad35141fabe1%26t%3D1648547505%26lm%3D%26lf%3D%26sk%3Dae9bf01b94828e0dab69423fb17a09ba%26mt%3D1648547505%26rc%3D%26v%3D2.0%26a%3D1",
                    "S": "",
                }
            )
                .validate()
                .assert_equal("status_code", 200)
                .assert_equal('headers."Content-Type"', "application/json; charset=utf-8")
                .assert_equal("body.errno", 0)
                .assert_equal("body.errmsg", "")
                .assert_equal("body.type", 0)
                .assert_equal("body.t_str", "")
        )
    ]
